# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  test:

services:

  ca_nextgeneral:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-nextgeneral
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7079
    ports:
      - "7079:7079" 
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../../organizations/fabric-ca/nextgeneral:/etc/hyperledger/fabric-ca-server
    container_name: ca_nextgeneral
    networks:
      - test



 
